In [3]:
import pandas as pd 
from pathlib import Path

data_raw = Path("../data/raw")

files = list(data_raw.iterdir())

for file in files:
    print(file.name)

.gitkeep
ACCESOS_INTERNET_FIJO_2_8.csv
ACCESOS_INTERNET_FIJO_3_5.csv
README.md

In [4]:
df1 = pd.read_csv(data_raw / "ACCESOS_INTERNET_FIJO_2_8.csv", sep=";")
df2 = pd.read_csv(data_raw / "ACCESOS_INTERNET_FIJO_3_5.csv", sep=";")

In [5]:
df1.head()

,ANNO,TRIMESTRE,ID_EMPRESA,EMPRESA,ID_MUNICIPIO,MUNICIPIO,ID_DEPARTAMENTO,DEPARTAMENTO,ID_SEGMENTO,SEGMENTO,VELOCIDAD_EFECTIVA_DOWNSTREAM,VELOCIDAD_EFECTIVA_UPSTREAM,ID_TECNOLOGIA,TECNOLOGIA,ACCESOS
0,2017,2,900092385,UNE EPM TELECOMUNICACIONES S.A.,63001,ARMENIA,63,QUINDÍO,103,Residencial - Estrato 3,2,1,106,Hybrid Fiber Coaxial (HFC),14
1,2017,2,900092385,UNE EPM TELECOMUNICACIONES S.A.,63001,ARMENIA,63,QUINDÍO,103,Residencial - Estrato 3,3,1,106,Hybrid Fiber Coaxial (HFC),1007
2,2017,2,900092385,UNE EPM TELECOMUNICACIONES S.A.,63001,ARMENIA,63,QUINDÍO,103,Residencial - Estrato 3,4,1,106,Hybrid Fiber Coaxial (HFC),166
3,2017,2,900092385,UNE EPM TELECOMUNICACIONES S.A.,63001,ARMENIA,63,QUINDÍO,103,Residencial - Estrato 3,5,1,106,Hybrid Fiber Coaxial (HFC),3857
4,2017,2,900092385,UNE EPM TELECOMUNICACIONES S.A.,63001,ARMENIA,63,QUINDÍO,103,Residencial - Estrato 3,10,1,106,Hybrid Fiber Coaxial (HFC),1314

In [6]:
df1.shape

(3288251, 15)

In [7]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3288251 entries, 0 to 3288250
Data columns (total 15 columns):
 #   Column                         Dtype
---  ------                         -----
 0   ANNO                           int64
 1   TRIMESTRE                      int64
 2   ID_EMPRESA                     int64
 3   EMPRESA                        object
 4   ID_MUNICIPIO                   int64
 5   MUNICIPIO                      object
 6   ID_DEPARTAMENTO                int64
 7   DEPARTAMENTO                   object
 8   ID_SEGMENTO                    int64
 9   SEGMENTO                       object
 10  VELOCIDAD_EFECTIVA_DOWNSTREAM  object
 11  VELOCIDAD_EFECTIVA_UPSTREAM    object
 12  ID_TECNOLOGIA                  int64
 13  TECNOLOGIA                     object
 14  ACCESOS                        int64
dtypes: int64(8), object(7)
memory usage: 376.3+ MB

In [8]:
df1.columns.to_list()

['ANNO',
 'TRIMESTRE',
 'ID_EMPRESA',
 'EMPRESA',
 'ID_MUNICIPIO',
 'MUNICIPIO',
 'ID_DEPARTAMENTO',
 'DEPARTAMENTO',
 'ID_SEGMENTO',
 'SEGMENTO',
 'VELOCIDAD_EFECTIVA_DOWNSTREAM',
 'VELOCIDAD_EFECTIVA_UPSTREAM',
 'ID_TECNOLOGIA',
 'TECNOLOGIA',
 'ACCESOS']

In [9]:
df1.isna().sum()

ANNO                               0
TRIMESTRE                          0
ID_EMPRESA                         0
EMPRESA                            0
ID_MUNICIPIO                       0
MUNICIPIO                          0
ID_DEPARTAMENTO                    0
DEPARTAMENTO                       0
ID_SEGMENTO                        0
SEGMENTO                           0
VELOCIDAD_EFECTIVA_DOWNSTREAM      0
VELOCIDAD_EFECTIVA_UPSTREAM        0
ID_TECNOLOGIA                      0
TECNOLOGIA                       129
ACCESOS                            0
dtype: int64

In [10]:
df1.dtypes

ANNO                              int64
TRIMESTRE                         int64
ID_EMPRESA                        int64
EMPRESA                          object
ID_MUNICIPIO                      int64
MUNICIPIO                        object
ID_DEPARTAMENTO                   int64
DEPARTAMENTO                     object
ID_SEGMENTO                       int64
SEGMENTO                         object
VELOCIDAD_EFECTIVA_DOWNSTREAM    object
VELOCIDAD_EFECTIVA_UPSTREAM      object
ID_TECNOLOGIA                     int64
TECNOLOGIA                       object
ACCESOS                           int64
dtype: object

Exploración inical df2.

In [11]:
df2.head()

,ANNO,TRIMESTRE,ID_EMPRESA,EMPRESA,ID_MUNICIPIO,MUNICIPIO,ID_DEPARTAMENTO,DEPARTAMENTO,ID_SEGMENTO,SEGMENTO,VELOCIDAD_EFECTIVA_DOWNSTREAM,VELOCIDAD_EFECTIVA_UPSTREAM,ID_TECNOLOGIA,TECNOLOGIA,ACCESOS
0,2024,1,10722639,RODRIGO CUSHCAGUA OYAGATA,19473,MORALES,19,CAUCA,107,Corporativo,5,5,108,Fiber to the home (FTTH),3
1,2024,1,10722639,RODRIGO CUSHCAGUA OYAGATA,19473,MORALES,19,CAUCA,107,Corporativo,9,9,108,Fiber to the home (FTTH),1
2,2024,1,10722639,RODRIGO CUSHCAGUA OYAGATA,19473,MORALES,19,CAUCA,107,Corporativo,10,10,108,Fiber to the home (FTTH),1
3,2024,1,10722639,RODRIGO CUSHCAGUA OYAGATA,19548,PIENDAMÓ,19,CAUCA,107,Corporativo,5,4,104,WiFi,3
4,2024,1,10722639,RODRIGO CUSHCAGUA OYAGATA,19548,PIENDAMÓ,19,CAUCA,107,Corporativo,5,5,108,Fiber to the home (FTTH),3

In [12]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 973335 entries, 0 to 973334
Data columns (total 15 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   ANNO                           973335 non-null  int64
 1   TRIMESTRE                      973335 non-null  int64
 2   ID_EMPRESA                     973335 non-null  int64
 3   EMPRESA                        973335 non-null  object
 4   ID_MUNICIPIO                   973335 non-null  int64
 5   MUNICIPIO                      973335 non-null  object
 6   ID_DEPARTAMENTO                973335 non-null  int64
 7   DEPARTAMENTO                   973335 non-null  object
 8   ID_SEGMENTO                    973335 non-null  int64
 9   SEGMENTO                       973335 non-null  object
 10  VELOCIDAD_EFECTIVA_DOWNSTREAM  973335 non-null  object
 11  VELOCIDAD_EFECTIVA_UPSTREAM    973335 non-null  object
 12  ID_TECNOLOGIA                  973335 non-null  int64
 13  TECNOLOGIA                     973263 non-null  object
 14  ACCESOS                        973335 non-null  int64
dtypes: int64(8), object(7)
memory usage: 111.4+ MB

In [13]:
df2.isna().sum()

ANNO                              0
TRIMESTRE                         0
ID_EMPRESA                        0
EMPRESA                           0
ID_MUNICIPIO                      0
MUNICIPIO                         0
ID_DEPARTAMENTO                   0
DEPARTAMENTO                      0
ID_SEGMENTO                       0
SEGMENTO                          0
VELOCIDAD_EFECTIVA_DOWNSTREAM     0
VELOCIDAD_EFECTIVA_UPSTREAM       0
ID_TECNOLOGIA                     0
TECNOLOGIA                       72
ACCESOS                           0
dtype: int64

In [14]:
df1["ANNO"].min(), df1["ANNO"].max(), df1["ANNO"].unique()

(2017,
 2026,
 array([2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026],
       dtype=int64))

In [15]:
df2["ANNO"].min(), df2["ANNO"].max(), df2["ANNO"].unique()

(2024, 2026, array([2024, 2025, 2026], dtype=int64))

In [16]:
df1["TRIMESTRE"].value_counts().sort_index()

TRIMESTRE
1    843173
2    799316
3    823108
4    822654
Name: count, dtype: int64

In [17]:
df2["TRIMESTRE"].value_counts().sort_index()

TRIMESTRE
1    323673
2    217104
3    217307
4    215251
Name: count, dtype: int64

In [18]:
df1.columns.equals(df2.columns)

True

In [19]:
set(df1.columns) - set(df2.columns)
set(df2.columns) - set(df1.columns)

set()

In [20]:
df1["VELOCIDAD_EFECTIVA_DOWNSTREAM"].value_counts().head(30)

VELOCIDAD_EFECTIVA_DOWNSTREAM
10     317806
5      168915
6      160116
20     159367
4      154822
2      151634
30     144575
100    137561
50     126346
3      120985
15     116470
1      101974
25     101275
200     93259
8       83725
300     75817
60      63016
12      60812
150     60426
40      60288
7       42448
500     40852
80      37791
120     36029
250     31466
400     25489
9       20024
75      17221
600     16658
70      16200
Name: count, dtype: int64

In [21]:
df1["VELOCIDAD_EFECTIVA_UPSTREAM"].value_counts().head(30)

VELOCIDAD_EFECTIVA_UPSTREAM
1       650191
10      223725
3       180662
5       179161
2       175684
30      134728
4       119648
6       108098
20       96085
50       91412
100      82286
0,5      81937
15       76863
8        69123
40       67264
25       57214
200      51825
12       39788
150      36726
300      30183
7        26576
60       25960
0,8      25481
2,5      24229
1,5      20940
1,02     20786
80       19497
250      18183
500      17568
75       15551
Name: count, dtype: int64

In [22]:
# Cobertura por año y trimestre
df1.groupby(["ANNO", "TRIMESTRE"]).size().unstack(fill_value=0)

TRIMESTRE       1       2       3       4
ANNO
2017            0   48570   50539   51901
2018        55048   56975   59331   62368
2019        66175   71886   77249   77860
2020        81915   86049   86333   87073
2021        94891   98012  102078  103916
2022       103368  106241  107838  110439
2023       118103  114479  122433  113846
2024       109119  110870  110558  109666
2025       108616  106234  106749  105585
2026       105938       0       0       0

In [23]:
# Cobertura por año y trimestre
df2.groupby(["ANNO", "TRIMESTRE"]).size().unstack(fill_value=0)

TRIMESTRE       1       2       3       4
ANNO
2024       109119  110870  110558  109666
2025       108616  106234  106749  105585
2026       105938       0       0       0

In [24]:
print("Archivo 1:", df1.shape)
print("Archivo 2:", df2.shape)

print("\nRango archivo 1:")
print(df1["ANNO"].min(), df1["ANNO"].max())

print("\nRango archivo 2:")
print(df2["ANNO"].min(), df2["ANNO"].max())

Archivo 1: (3288251, 15)
Archivo 2: (973335, 15)

Rango archivo 1:
2017 2026

Rango archivo 2:
2024 2026

In [25]:
# Cantidad de accesos por año
df1.groupby("ANNO")["ACCESOS"].sum()

ANNO
2017    18831122
2018    26450155
2019    27709758
2020    30192859
2021    33219073
2022    34972656
2023    36317390
2024    36464207
2025    39704055
2026    10502356
Name: ACCESOS, dtype: int64

In [26]:
df_q4 = (
    df1[df1["TRIMESTRE"] == 4]
    .groupby("ANNO", as_index=False)["ACCESOS"]
    .sum()
)

df_q4

   ANNO   ACCESOS
0  2017   6352946
1  2018   6731666
2  2019   6984242
3  2020   7837355
4  2021   8454845
5  2022   8841612
6  2023   9064552
7  2024   9278294
8  2025  10325111

calculamos crecimiento

In [28]:
df_q4["CAMBIO_ABSOLUTO"] = df_q4["ACCESOS"].diff()

df_q4["CAMBIO_PORCENTUAL"] = (
    df_q4["ACCESOS"].pct_change() * 100
)

df_q4

   ANNO   ACCESOS  CAMBIO_ABSOLUTO  CAMBIO_PORCENTUAL
0  2017   6352946              NaN                NaN
1  2018   6731666         378720.0           5.961329
2  2019   6984242         252576.0           3.752058
3  2020   7837355         853113.0          12.214826
4  2021   8454845         617490.0           7.878806
5  2022   8841612         386767.0           4.574501
6  2023   9064552         222940.0           2.521486
7  2024   9278294         213742.0           2.357998
8  2025  10325111        1046817.0          11.282430

In [29]:
df1["SEGMENTO"].value_counts()

SEGMENTO
Corporativo                           1166974
Residencial - Estrato 2                663343
Residencial - Estrato 1                523449
Residencial - Estrato 3                431273
Residencial - Estrato 4                219480
Residencial - Estrato 5                107742
Residencial - Estrato 6                 85175
Sin estratificar                        73338
Uso propio interno del operador         13019
Corporativo  (accesos adicionales)       4458
Name: count, dtype: int64

In [30]:
df1[["ID_SEGMENTO", "SEGMENTO"]].drop_duplicates().sort_values("ID_SEGMENTO")

         ID_SEGMENTO                            SEGMENTO
59               101             Residencial - Estrato 1
58               102             Residencial - Estrato 2
0                103             Residencial - Estrato 3
6                104             Residencial - Estrato 4
13               105             Residencial - Estrato 5
21               106             Residencial - Estrato 6
32               107                         Corporativo
23               108                    Sin estratificar
1419444          109     Uso propio interno del operador
2318013          117  Corporativo  (accesos adicionales)

In [31]:
residenciales = df1[
    df1["SEGMENTO"].str.startswith("Residencial")
].copy()

residenciales.groupby("SEGMENTO")["ACCESOS"].sum().sort_values(ascending=False)

SEGMENTO
Residencial - Estrato 2    103845582
Residencial - Estrato 3     81357469
Residencial - Estrato 1     33515071
Residencial - Estrato 4     30696064
Residencial - Estrato 5      9747840
Residencial - Estrato 6      7221854
Name: ACCESOS, dtype: int64

Quiero saber qué proporción del universo residencial corresponde a cada estrato.

In [32]:
residenciales.groupby("SEGMENTO")["ACCESOS"].sum() / residenciales["ACCESOS"].sum()

SEGMENTO
Residencial - Estrato 1    0.125815
Residencial - Estrato 2    0.389834
Residencial - Estrato 3    0.305414
Residencial - Estrato 4    0.115232
Residencial - Estrato 5    0.036593
Residencial - Estrato 6    0.027111
Name: ACCESOS, dtype: float64

In [33]:
estrato_anual = (
    residenciales
    .groupby(["ANNO", "SEGMENTO"], as_index=False)["ACCESOS"]
    .sum()
)

estrato_anual.head()

   ANNO                 SEGMENTO  ACCESOS
0  2017  Residencial - Estrato 1  1933317
1  2017  Residencial - Estrato 2  6509933
2  2017  Residencial - Estrato 3  5352127
3  2017  Residencial - Estrato 4  2093458
4  2017  Residencial - Estrato 5   688958

debemos decidir si usamos Q4 de cada año.

In [35]:
residenciales_q4 = residenciales[
    residenciales["TRIMESTRE"] == 4
].copy()

estrato_q4 = (
    residenciales_q4
    .groupby(["ANNO", "SEGMENTO"], as_index=False)["ACCESOS"]
    .sum()
)

residenciales_q4.head()

,ANNO,TRIMESTRE,ID_EMPRESA,EMPRESA,ID_MUNICIPIO,MUNICIPIO,ID_DEPARTAMENTO,DEPARTAMENTO,ID_SEGMENTO,SEGMENTO,VELOCIDAD_EFECTIVA_DOWNSTREAM,VELOCIDAD_EFECTIVA_UPSTREAM,ID_TECNOLOGIA,TECNOLOGIA,ACCESOS
99115,2017,4,890003081,ELECTRONICA Y TELECOMUNICACIONES DE COLOMBIA S...,66001,PEREIRA,66,RISARALDA,105,Residencial - Estrato 5,3,2,104,WiFi,1
99116,2017,4,890003081,ELECTRONICA Y TELECOMUNICACIONES DE COLOMBIA S...,63190,CIRCASIA,63,QUINDÍO,102,Residencial - Estrato 2,1,1,104,WiFi,1
99119,2017,4,890003081,ELECTRONICA Y TELECOMUNICACIONES DE COLOMBIA S...,66088,BELÉN DE UMBRÍA,66,RISARALDA,102,Residencial - Estrato 2,1,1,104,WiFi,1
99123,2017,4,890003081,ELECTRONICA Y TELECOMUNICACIONES DE COLOMBIA S...,66001,PEREIRA,66,RISARALDA,102,Residencial - Estrato 2,3,2,104,WiFi,1
99124,2017,4,890003081,ELECTRONICA Y TELECOMUNICACIONES DE COLOMBIA S...,66088,BELÉN DE UMBRÍA,66,RISARALDA,101,Residencial - Estrato 1,2,1,104,WiFi,1

# primera gráfica

Evolución de los 6 estratos.

In [36]:
estrato_q4 = (
    residenciales_q4
    .groupby(["ANNO", "SEGMENTO"], as_index=False)["ACCESOS"]
    .sum()
)

estrato_pivot = (
    estrato_q4
    .pivot(index="ANNO", columns="SEGMENTO", values="ACCESOS")
)

estrato_pivot

SEGMENTO,Residencial - Estrato 1,Residencial - Estrato 2,Residencial - Estrato 3,Residencial - Estrato 4,Residencial - Estrato 5,Residencial - Estrato 6
ANNO,,,,,,
2017,687170,2164659,1796065,711083,232036,169578
2018,668604,2348570,1854413,778737,255108,186039
2019,666933,2464090,1955641,831580,249125,188016
2020,853237,2869772,2165895,863603,255215,198707
2021,979261,3052581,2307569,883307,268973,215195
2022,1024007,3054827,2429539,923650,279432,210941
2023,1060203,3153726,2511874,896433,295828,217641
2024,1094403,3249882,2579195,885869,299838,216275
2025,1356963,3647684,2806953,928507,315876,218060

calculamos el cambio 2017 → 2025

In [37]:
cambio_estrato = pd.DataFrame({
    "accesos_2017": estrato_pivot.loc[2017],
    "accesos_2025": estrato_pivot.loc[2025]
})

cambio_estrato["cambio_absoluto"] = (
    cambio_estrato["accesos_2025"] -
    cambio_estrato["accesos_2017"]
)

cambio_estrato["cambio_%"] = (
    cambio_estrato["accesos_2025"] /
    cambio_estrato["accesos_2017"] - 1
) * 100

cambio_estrato.sort_values("cambio_%", ascending=False)

,accesos_2017,accesos_2025,cambio_absoluto,cambio_%
SEGMENTO,,,,
Residencial - Estrato 1,687170,1356963,669793,97.471223
Residencial - Estrato 2,2164659,3647684,1483025,68.510791
Residencial - Estrato 3,1796065,2806953,1010888,56.283486
Residencial - Estrato 5,232036,315876,83840,36.132324
Residencial - Estrato 4,711083,928507,217424,30.576459
Residencial - Estrato 6,169578,218060,48482,28.589793

Pregunta 2
¿Dónde está la brecha territorial?

In [38]:
municipal_q4 = (
    residenciales_q4
    .groupby(
        [
            "ID_MUNICIPIO",
            "MUNICIPIO",
            "ID_DEPARTAMENTO",
            "DEPARTAMENTO",
            "ANNO"
        ],
        as_index=False
    )["ACCESOS"]
    .sum()
)

In [39]:
municipal_cambio = (
    municipal_q4
    .pivot_table(
        index=[
            "ID_MUNICIPIO",
            "MUNICIPIO",
            "ID_DEPARTAMENTO",
            "DEPARTAMENTO"
        ],
        columns="ANNO",
        values="ACCESOS",
        fill_value=0
    )
    .reset_index()
)

In [40]:
municipal_cambio = municipal_cambio[
    [
        "ID_MUNICIPIO",
        "MUNICIPIO",
        "ID_DEPARTAMENTO",
        "DEPARTAMENTO",
        2017,
        2025
    ]
].copy()

municipal_cambio = municipal_cambio.rename(
    columns={
        2017: "ACCESOS_2017",
        2025: "ACCESOS_2025"
    }
)

In [41]:
municipal_cambio["CAMBIO_ABSOLUTO"] = (
    municipal_cambio["ACCESOS_2025"] -
    municipal_cambio["ACCESOS_2017"]
)

municipal_cambio["CAMBIO_%"] = (
    (municipal_cambio["ACCESOS_2025"] /
     municipal_cambio["ACCESOS_2017"]) - 1
) * 100

Mayores crecimientos relativos

In [42]:
municipal_cambio.sort_values(
    "CAMBIO_%",
    ascending=False
).head(20)

ANNO,ID_MUNICIPIO,MUNICIPIO,ID_DEPARTAMENTO,DEPARTAMENTO,ACCESOS_2017,ACCESOS_2025,CAMBIO_ABSOLUTO,CAMBIO_%
1210,99773,CUMARIBO,99,VICHADA,0.0,163.0,163.0,inf
1067,73270,FALÁN,73,TOLIMA,0.0,292.0,292.0,inf
447,20383,LA GLORIA,20,CESAR,0.0,850.0,850.0,inf
446,20310,GONZÁLEZ,20,CESAR,0.0,66.0,66.0,inf
445,20295,GAMARRA,20,CESAR,0.0,709.0,709.0,inf
443,20238,EL COPEY,20,CESAR,0.0,2600.0,2600.0,inf
442,20228,CURUMANÍ,20,CESAR,0.0,1570.0,1570.0,inf
440,20175,CHIMICHAGUA,20,CESAR,0.0,407.0,407.0,inf
973,68327,GUOUEPSA,68,SANTANDER,0.0,29.0,29.0,inf
438,20045,BECERRIL,20,CESAR,0.0,748.0,748.0,inf
141,8436,MANATÍ,8,ATLÁNTICO,0.0,1149.0,1149.0,inf
437,20032,ASTREA,20,CESAR,0.0,305.0,305.0,inf
143,8549,PIOJÓ,8,ATLÁNTICO,0.0,141.0,141.0,inf
144,8558,POLONUEVO,8,ATLÁNTICO,0.0,680.0,680.0,inf
432,19824,TOTORÓ,19,CAUCA,0.0,92.0,92.0,inf
431,19821,TORIBIO,19,CAUCA,0.0,800.0,800.0,inf
430,19809,TIMBIQUÍ,19,CAUCA,0.0,256.0,256.0,inf
427,19780,SUÁREZ,19,CAUCA,0.0,1177.0,1177.0,inf
425,19760,SOTARÁ,19,CAUCA,0.0,22.0,22.0,inf
150,8675,SANTA LUCÍA,8,ATLÁNTICO,0.0,410.0,410.0,inf

Mayores aumentos absolutos

In [43]:
municipal_cambio.sort_values(
    "CAMBIO_ABSOLUTO",
    ascending=False
).head(20)

ANNO,ID_MUNICIPIO,MUNICIPIO,ID_DEPARTAMENTO,DEPARTAMENTO,ACCESOS_2017,ACCESOS_2025,CAMBIO_ABSOLUTO,CAMBIO_%
156,11001,BOGOTÁ,11,BOGOTÁ D.C.,0.0,2250053.0,2250053.0,inf
0,5001,MEDELLÍN,5,ANTIOQUIA,519915.0,775850.0,255935.0,49.226316
826,54001,CÚCUTA,54,NORTE SANTANDER,0.0,132385.0,132385.0,inf
158,13001,CARTAGENA,13,BOLÍVAR,127060.0,247160.0,120100.0,94.522273
579,25754,SOACHA,25,CUNDINAMARCA,86653.0,193189.0,106536.0,122.945541
1050,73001,IBAGUÉ,73,TOLIMA,93005.0,190276.0,97271.0,104.586850
1099,76001,CALI,76,VALLE DEL CAUCA,421691.0,518607.0,96916.0,22.982705
61,5360,ITAGUÍ,5,ANTIOQUIA,0.0,93114.0,93114.0,inf
133,8001,BARRANQUILLA,8,ATLÁNTICO,191735.0,276618.0,84883.0,44.270999
18,5088,BELLO,5,ANTIOQUIA,94884.0,176311.0,81427.0,85.817419
696,47001,SANTA MARTA,47,MAGDALENA,65186.0,119935.0,54749.0,83.988893
919,66001,PEREIRA,66,RISARALDA,81092.0,129232.0,48140.0,59.364672
434,20001,VALLEDUPAR,20,CESAR,52728.0,99434.0,46706.0,88.579123
728,50001,VILLAVICENCIO,50,META,74825.0,117911.0,43086.0,57.582359
906,63001,ARMENIA,63,QUINDÍO,59695.0,93491.0,33796.0,56.614457
1126,76520,PALMIRA,76,VALLE DEL CAUCA,54506.0,87536.0,33030.0,60.598833
459,23001,MONTERÍA,23,CÓRDOBA,41687.0,74011.0,32324.0,77.539761
389,19001,POPAYÁN,19,CAUCA,46773.0,78802.0,32029.0,68.477540
152,8758,SOLEDAD,8,ATLÁNTICO,73140.0,104407.0,31267.0,42.749521
330,17001,MANIZALES,17,CALDAS,74952.0,106200.0,31248.0,41.690682

Municipios con una base mínima en 2017

In [44]:
municipal_cambio[
    municipal_cambio["ACCESOS_2017"] >= 1000
].sort_values(
    "CAMBIO_%",
    ascending=False
).head(20)

ANNO,ID_MUNICIPIO,MUNICIPIO,ID_DEPARTAMENTO,DEPARTAMENTO,ACCESOS_2017,ACCESOS_2025,CAMBIO_ABSOLUTO,CAMBIO_%
593,25817,TOCANCIPÁ,25,CUNDINAMARCA,4183.0,20574.0,16391.0,391.847956
332,17042,ANSERMA,17,CALDAS,1096.0,5140.0,4044.0,368.978102
1147,81736,SARAVENA,81,ARAUCA,2092.0,9661.0,7569.0,361.806883
256,15407,VILLA DE LEYVA,15,BOYACÁ,1038.0,4624.0,3586.0,345.472062
6,5034,ANDES,5,ANTIOQUIA,2459.0,10918.0,8459.0,344.001627
530,25320,GUADUAS,25,CUNDINAMARCA,1325.0,5736.0,4411.0,332.905660
695,44874,VILLANUEVA,44,LA GUAJIRA,1107.0,4765.0,3658.0,330.442638
568,25612,RICAURTE,25,CUNDINAMARCA,1100.0,4695.0,3595.0,326.818182
79,5541,PEÑOL,5,ANTIOQUIA,1235.0,5123.0,3888.0,314.817814
162,13052,ARJONA,13,BOLÍVAR,2255.0,9091.0,6836.0,303.148559
148,8634,SABANAGRANDE,8,ATLÁNTICO,1021.0,3767.0,2746.0,268.952008
1112,76233,DAGUA,76,VALLE DEL CAUCA,1037.0,3726.0,2689.0,259.305689
824,52838,TÚQUERRES,52,NARIÑO,1060.0,3730.0,2670.0,251.886792
661,41396,LA PLATA,41,HUILA,1520.0,5174.0,3654.0,240.394737
586,25785,TABIO,25,CUNDINAMARCA,1653.0,5590.0,3937.0,238.173019
589,25799,TENJO,25,CUNDINAMARCA,1340.0,4482.0,3142.0,234.477612
71,5440,MARINILLA,5,ANTIOQUIA,6622.0,21748.0,15126.0,228.420417
68,5400,LA UNIÓN,5,ANTIOQUIA,1848.0,6025.0,4177.0,226.028139
1072,73349,HONDA,73,TOLIMA,2232.0,7245.0,5013.0,224.596774
271,15516,PAIPA,15,BOYACÁ,2657.0,8577.0,5920.0,222.807678

Los municipios que más retrocedieron

In [45]:
municipal_cambio.sort_values(
    "CAMBIO_%",
    ascending=True
).head(20)

ANNO,ID_MUNICIPIO,MUNICIPIO,ID_DEPARTAMENTO,DEPARTAMENTO,ACCESOS_2017,ACCESOS_2025,CAMBIO_ABSOLUTO,CAMBIO_%
377,18592,PUERTO RICO,18,CAQUETA,411.0,0.0,-411.0,-100.0
381,18753,SAN VICENTE DEL CAGUÁN,18,CAQUETA,466.0,0.0,-466.0,-100.0
878,54520,PAMPLONITA,54,NORTE DE SANTANDER,14.0,0.0,-14.0,-100.0
876,54518,PAMPLONA,54,NORTE DE SANTANDER,5391.0,0.0,-5391.0,-100.0
874,54498,OCAÑA,54,NORTE DE SANTANDER,7577.0,0.0,-7577.0,-100.0
872,54480,MUTISCUA,54,NORTE DE SANTANDER,39.0,0.0,-39.0,-100.0
868,54405,LOS PATIOS,54,NORTE DE SANTANDER,10127.0,0.0,-10127.0,-100.0
1066,73270,FALAN,73,TOLIMA,130.0,0.0,-130.0,-100.0
866,54398,LA PLAYA,54,NORTE DE SANTANDER,72.0,0.0,-72.0,-100.0
862,54377,LABATECA,54,NORTE DE SANTANDER,63.0,0.0,-63.0,-100.0
860,54347,HERRÁN,54,NORTE DE SANTANDER,10.0,0.0,-10.0,-100.0
856,54313,GRAMALOTE,54,NORTE DE SANTANDER,13.0,0.0,-13.0,-100.0
854,54261,EL ZULIA,54,NORTE DE SANTANDER,33.0,0.0,-33.0,-100.0
852,54250,EL TARRA,54,NORTE DE SANTANDER,311.0,0.0,-311.0,-100.0
1077,73443,MARIQUITA - SAN SEBASTIÁN DE MARIQUITA,73,TOLIMA,2296.0,0.0,-2296.0,-100.0
850,54245,EL CARMEN,54,NORTE DE SANTANDER,66.0,0.0,-66.0,-100.0
848,54239,DURANIA,54,NORTE DE SANTANDER,64.0,0.0,-64.0,-100.0
846,54223,CUCUTILLA,54,NORTE DE SANTANDER,45.0,0.0,-45.0,-100.0
844,54206,CONVENCIÓN,54,NORTE DE SANTANDER,90.0,0.0,-90.0,-100.0
842,54174,CHITAGÁ,54,NORTE DE SANTANDER,91.0,0.0,-91.0,-100.0

Municipios con información comparable en ambos extremos del período.

In [47]:
df1.columns.tolist()

['ANNO',
 'TRIMESTRE',
 'ID_EMPRESA',
 'EMPRESA',
 'ID_MUNICIPIO',
 'MUNICIPIO',
 'ID_DEPARTAMENTO',
 'DEPARTAMENTO',
 'ID_SEGMENTO',
 'SEGMENTO',
 'VELOCIDAD_EFECTIVA_DOWNSTREAM',
 'VELOCIDAD_EFECTIVA_UPSTREAM',
 'ID_TECNOLOGIA',
 'TECNOLOGIA',
 'ACCESOS']

In [48]:
# Nos quedamos únicamente con Q4
df_q4 = df1[df1["TRIMESTRE"] == 4].copy()

In [49]:
municipios_anual = (
    df_q4
    .groupby(
        [
            "ANNO",
            "ID_MUNICIPIO",
            "MUNICIPIO",
            "ID_DEPARTAMENTO",
            "DEPARTAMENTO"
        ],
        as_index=False
    )["ACCESOS"]
    .sum()
)

hacemos el pivot

In [50]:
municipios_pivot = (
    municipios_anual
    .pivot_table(
        index=[
            "ID_MUNICIPIO",
            "MUNICIPIO",
            "ID_DEPARTAMENTO",
            "DEPARTAMENTO"
        ],
        columns="ANNO",
        values="ACCESOS",
        fill_value=0
    )
    .reset_index()
)

In [51]:
municipios_pivot.columns.name = None

renombramos

In [52]:
municipios_pivot = municipios_pivot.rename(
    columns={
        2017: "ACCESOS_2017",
        2025: "ACCESOS_2025"
    }
)

In [53]:
ranking_municipios = municipios_pivot[
    (municipios_pivot["ACCESOS_2017"] > 0) &
    (municipios_pivot["ACCESOS_2025"] > 0)
].copy()

In [54]:
ranking_municipios["CAMBIO_ABSOLUTO"] = (
    ranking_municipios["ACCESOS_2025"] -
    ranking_municipios["ACCESOS_2017"]
)

ranking_municipios["CAMBIO_%"] = (
    ranking_municipios["CAMBIO_ABSOLUTO"] /
    ranking_municipios["ACCESOS_2017"]
) * 100

In [56]:
ranking_municipios.head()

,ID_MUNICIPIO,MUNICIPIO,ID_DEPARTAMENTO,DEPARTAMENTO,ACCESOS_2017,2018,2019,2020,2021,2022,2023,2024,ACCESOS_2025,CAMBIO_ABSOLUTO,CAMBIO_%
0,5001,MEDELLÍN,5,ANTIOQUIA,569520.0,592660.0,618829.0,668360.0,702797.0,768450.0,772346.0,791436.0,850323.0,280803.0,49.305204
1,5002,ABEJORRAL,5,ANTIOQUIA,962.0,1037.0,1074.0,24735.0,2230.0,2320.0,948.0,697.0,507.0,-455.0,-47.297297
2,5004,ABRIAQUÍ,5,ANTIOQUIA,65.0,71.0,83.0,134.0,155.0,147.0,152.0,190.0,237.0,172.0,264.615385
3,5021,ALEJANDRÍA,5,ANTIOQUIA,289.0,317.0,303.0,224.0,335.0,291.0,305.0,399.0,377.0,88.0,30.449827
4,5030,AMAGÁ,5,ANTIOQUIA,2668.0,3005.0,3181.0,2988.0,3760.0,3469.0,4253.0,4976.0,4894.0,2226.0,83.433283

Retomamos preguntas con los datos solidos despues de aplicar pivot.

Ranking por crecimiento porcentual

In [57]:
top_crecimiento = (
    ranking_municipios
    .sort_values("CAMBIO_%", ascending=False)
    [[
        "MUNICIPIO",
        "DEPARTAMENTO",
        "ACCESOS_2017",
        "ACCESOS_2025",
        "CAMBIO_ABSOLUTO",
        "CAMBIO_%"
    ]]
    .head(20)
)

top_crecimiento

,MUNICIPIO,DEPARTAMENTO,ACCESOS_2017,ACCESOS_2025,CAMBIO_ABSOLUTO,CAMBIO_%
144,POLONUEVO,ATLÁNTICO,1.0,737.0,736.0,73600.000000
792,LA LLANADA,NARIÑO,2.0,1123.0,1121.0,56050.000000
155,USIACURÍ,ATLÁNTICO,2.0,933.0,931.0,46550.000000
141,MANATÍ,ATLÁNTICO,3.0,1191.0,1188.0,39600.000000
400,FLORENCIA,CAUCA,7.0,2669.0,2662.0,38028.571429
401,GUACHENÉ,CAUCA,7.0,1871.0,1864.0,26628.571429
671,SALADOBLANCO,HUILA,12.0,2606.0,2594.0,21616.666667
818,SANTA BÁRBARA,NARIÑO,2.0,354.0,352.0,17600.000000
1146,FORTUL,ARAUCA,13.0,2182.0,2169.0,16684.615385
150,SANTA LUCÍA,ATLÁNTICO,3.0,431.0,428.0,14266.666667
776,CUMBITARA,NARIÑO,3.0,417.0,414.0,13800.000000
797,LOS ANDES,NARIÑO,5.0,680.0,675.0,13500.000000
398,CORINTO,CAUCA,26.0,3503.0,3477.0,13373.076923
1173,PUERTO CAICEDO,PUTUMAYO,16.0,1888.0,1872.0,11700.000000
1044,SAN PEDRO,SUCRE,11.0,1275.0,1264.0,11490.909091
443,EL COPEY,CESAR,25.0,2810.0,2785.0,11140.000000
442,CURUMANÍ,CESAR,26.0,2782.0,2756.0,10600.000000
780,EL ROSARIO,NARIÑO,6.0,611.0,605.0,10083.333333
1178,SAN MIGUEL,PUTUMAYO,17.0,1718.0,1701.0,10005.882353
646,ACEVEDO,HUILA,35.0,3532.0,3497.0,9991.428571

Ranking por crecimiento absoluto

In [58]:
top_absoluto = (
    ranking_municipios
    .sort_values("CAMBIO_ABSOLUTO", ascending=False)
    [[
        "MUNICIPIO",
        "DEPARTAMENTO",
        "ACCESOS_2017",
        "ACCESOS_2025",
        "CAMBIO_ABSOLUTO",
        "CAMBIO_%"
    ]]
    .head(20)
)

top_absoluto

,MUNICIPIO,DEPARTAMENTO,ACCESOS_2017,ACCESOS_2025,CAMBIO_ABSOLUTO,CAMBIO_%
0,MEDELLÍN,ANTIOQUIA,569520.0,850323.0,280803.0,49.305204
158,CARTAGENA,BOLÍVAR,142665.0,265185.0,122520.0,85.879508
1100,CALI,VALLE DEL CAUCA,454577.0,572684.0,118107.0,25.981737
579,SOACHA,CUNDINAMARCA,89670.0,198821.0,109151.0,121.725215
1051,IBAGUÉ,TOLIMA,103231.0,205327.0,102096.0,98.900524
18,BELLO,ANTIOQUIA,97794.0,181663.0,83869.0,85.760885
133,BARRANQUILLA,ATLÁNTICO,221576.0,305081.0,83505.0,37.686843
697,SANTA MARTA,MAGDALENA,73391.0,129927.0,56536.0,77.033969
920,PEREIRA,RISARALDA,90480.0,146865.0,56385.0,62.317639
729,VILLAVICENCIO,META,84309.0,138300.0,53991.0,64.039426
434,VALLEDUPAR,CESAR,61050.0,106889.0,45839.0,75.084357
1127,PALMIRA,VALLE DEL CAUCA,57283.0,93021.0,35738.0,62.388492
907,ARMENIA,QUINDÍO,66592.0,100706.0,34114.0,51.228376
459,MONTERÍA,CÓRDOBA,47503.0,81509.0,34006.0,71.587058
389,POPAYÁN,CAUCA,50442.0,84127.0,33685.0,66.779668
330,MANIZALES,CALDAS,81795.0,115231.0,33436.0,40.877804
547,MADRID,CUNDINAMARCA,17193.0,49585.0,32392.0,188.402257
645,NEIVA,HUILA,70122.0,102299.0,32177.0,45.887168
152,SOLEDAD,ATLÁNTICO,74951.0,106879.0,31928.0,42.598498
1122,JAMUNDÍ,VALLE DEL CAUCA,24805.0,56017.0,31212.0,125.829470

Crecimiento relativo: ¿dónde aumentó más la conectividad respecto al punto de partida?

Crecimiento absoluto: ¿dónde se incorporaron más accesos?

In [60]:
ranking_municipios.sort_values(
    "CAMBIO_ABSOLUTO",
    ascending=False
).head(20)

,ID_MUNICIPIO,MUNICIPIO,ID_DEPARTAMENTO,DEPARTAMENTO,ACCESOS_2017,2018,2019,2020,2021,2022,2023,2024,ACCESOS_2025,CAMBIO_ABSOLUTO,CAMBIO_%
0,5001,MEDELLÍN,5,ANTIOQUIA,569520.0,592660.0,618829.0,668360.0,702797.0,768450.0,772346.0,791436.0,850323.0,280803.0,49.305204
158,13001,CARTAGENA,13,BOLÍVAR,142665.0,150644.0,156717.0,165142.0,182011.0,196520.0,194654.0,227997.0,265185.0,122520.0,85.879508
1100,76001,CALI,76,VALLE DEL CAUCA,454577.0,476379.0,496134.0,535991.0,554163.0,548254.0,680309.0,550488.0,572684.0,118107.0,25.981737
579,25754,SOACHA,25,CUNDINAMARCA,89670.0,113941.0,116237.0,146458.0,161699.0,162981.0,168123.0,186200.0,198821.0,109151.0,121.725215
1051,73001,IBAGUÉ,73,TOLIMA,103231.0,109901.0,114885.0,129726.0,143869.0,152525.0,157669.0,167251.0,205327.0,102096.0,98.900524
18,5088,BELLO,5,ANTIOQUIA,97794.0,105569.0,111401.0,124110.0,132308.0,142732.0,144377.0,164071.0,181663.0,83869.0,85.760885
133,8001,BARRANQUILLA,8,ATLÁNTICO,221576.0,190668.0,241105.0,256255.0,268119.0,297555.0,292511.0,278131.0,305081.0,83505.0,37.686843
697,47001,SANTA MARTA,47,MAGDALENA,73391.0,74758.0,83088.0,90361.0,103942.0,107170.0,105382.0,114201.0,129927.0,56536.0,77.033969
920,66001,PEREIRA,66,RISARALDA,90480.0,103880.0,110065.0,126696.0,135324.0,137723.0,129133.0,135666.0,146865.0,56385.0,62.317639
729,50001,VILLAVICENCIO,50,META,84309.0,91713.0,98945.0,107996.0,109810.0,117634.0,115544.0,123806.0,138300.0,53991.0,64.039426
434,20001,VALLEDUPAR,20,CESAR,61050.0,67667.0,71933.0,83075.0,85347.0,88239.0,86541.0,94113.0,106889.0,45839.0,75.084357
1127,76520,PALMIRA,76,VALLE DEL CAUCA,57283.0,60743.0,64277.0,70230.0,74386.0,82253.0,83337.0,84090.0,93021.0,35738.0,62.388492
907,63001,ARMENIA,63,QUINDÍO,66592.0,72609.0,75457.0,86125.0,90264.0,92893.0,90832.0,93732.0,100706.0,34114.0,51.228376
459,23001,MONTERÍA,23,CÓRDOBA,47503.0,54105.0,57647.0,63828.0,68170.0,68841.0,68834.0,71101.0,81509.0,34006.0,71.587058
389,19001,POPAYÁN,19,CAUCA,50442.0,57536.0,57854.0,63295.0,65401.0,69370.0,68731.0,70865.0,84127.0,33685.0,66.779668
330,17001,MANIZALES,17,CALDAS,81795.0,83560.0,85887.0,95897.0,97279.0,102899.0,103105.0,107299.0,115231.0,33436.0,40.877804
547,25430,MADRID,25,CUNDINAMARCA,17193.0,20217.0,24476.0,38338.0,36354.0,39567.0,43283.0,46142.0,49585.0,32392.0,188.402257
645,41001,NEIVA,41,HUILA,70122.0,75248.0,77527.0,86351.0,92872.0,95718.0,93814.0,93677.0,102299.0,32177.0,45.887168
152,8758,SOLEDAD,8,ATLÁNTICO,74951.0,59803.0,77137.0,90805.0,103822.0,107581.0,105440.0,102077.0,106879.0,31928.0,42.598498
1122,76364,JAMUNDÍ,76,VALLE DEL CAUCA,24805.0,27769.0,30216.0,38343.0,40061.0,46402.0,53994.0,50257.0,56017.0,31212.0,125.829470

In [61]:
ranking_municipios.sort_values(
    "CAMBIO_%",
    ascending=False
).head(20)

,ID_MUNICIPIO,MUNICIPIO,ID_DEPARTAMENTO,DEPARTAMENTO,ACCESOS_2017,2018,2019,2020,2021,2022,2023,2024,ACCESOS_2025,CAMBIO_ABSOLUTO,CAMBIO_%
144,8558,POLONUEVO,8,ATLÁNTICO,1.0,36.0,10.0,11.0,352.0,349.0,260.0,342.0,737.0,736.0,73600.000000
792,52385,LA LLANADA,52,NARIÑO,2.0,21.0,4.0,450.0,561.0,571.0,624.0,640.0,1123.0,1121.0,56050.000000
155,8849,USIACURÍ,8,ATLÁNTICO,2.0,7.0,10.0,8.0,228.0,1137.0,648.0,787.0,933.0,931.0,46550.000000
141,8436,MANATÍ,8,ATLÁNTICO,3.0,15.0,33.0,95.0,834.0,875.0,808.0,955.0,1191.0,1188.0,39600.000000
400,19290,FLORENCIA,19,CAUCA,7.0,197.0,451.0,675.0,1020.0,658.0,705.0,805.0,2669.0,2662.0,38028.571429
401,19300,GUACHENÉ,19,CAUCA,7.0,6.0,14.0,21.0,22.0,19.0,1076.0,1147.0,1871.0,1864.0,26628.571429
671,41660,SALADOBLANCO,41,HUILA,12.0,10.0,12.0,12.0,66.0,478.0,579.0,506.0,2606.0,2594.0,21616.666667
818,52696,SANTA BÁRBARA,52,NARIÑO,2.0,6.0,21.0,23.0,44.0,40.0,77.0,195.0,354.0,352.0,17600.000000
1146,81300,FORTUL,81,ARAUCA,13.0,19.0,521.0,1000.0,1177.0,1253.0,1540.0,1671.0,2182.0,2169.0,16684.615385
150,8675,SANTA LUCÍA,8,ATLÁNTICO,3.0,2.0,4.0,15.0,294.0,289.0,160.0,171.0,431.0,428.0,14266.666667
776,52233,CUMBITARA,52,NARIÑO,3.0,7.0,8.0,30.0,27.0,30.0,233.0,299.0,417.0,414.0,13800.000000
797,52418,LOS ANDES,52,NARIÑO,5.0,18.0,6.0,229.0,633.0,730.0,819.0,402.0,680.0,675.0,13500.000000
398,19212,CORINTO,19,CAUCA,26.0,33.0,194.0,182.0,136.0,955.0,967.0,1471.0,3503.0,3477.0,13373.076923
1173,86569,PUERTO CAICEDO,86,PUTUMAYO,16.0,30.0,33.0,762.0,857.0,73.0,42.0,859.0,1888.0,1872.0,11700.000000
1044,70717,SAN PEDRO,70,SUCRE,11.0,13.0,11.0,13.0,424.0,1036.0,1022.0,1138.0,1275.0,1264.0,11490.909091
443,20238,EL COPEY,20,CESAR,25.0,27.0,31.0,581.0,641.0,559.0,1225.0,1943.0,2810.0,2785.0,11140.000000
442,20228,CURUMANÍ,20,CESAR,26.0,112.0,587.0,714.0,852.0,1738.0,1275.0,2182.0,2782.0,2756.0,10600.000000
780,52256,EL ROSARIO,52,NARIÑO,6.0,23.0,13.0,88.0,142.0,224.0,453.0,499.0,611.0,605.0,10083.333333
1178,86757,SAN MIGUEL,86,PUTUMAYO,17.0,33.0,65.0,231.0,504.0,512.0,403.0,588.0,1718.0,1701.0,10005.882353
646,41006,ACEVEDO,41,HUILA,35.0,30.0,1337.0,2079.0,2932.0,2873.0,2853.0,3427.0,3532.0,3497.0,9991.428571

In [62]:
ranking_municipios.sort_values(
    "CAMBIO_ABSOLUTO",
    ascending=True
).head(20)

,ID_MUNICIPIO,MUNICIPIO,ID_DEPARTAMENTO,DEPARTAMENTO,ACCESOS_2017,2018,2019,2020,2021,2022,2023,2024,ACCESOS_2025,CAMBIO_ABSOLUTO,CAMBIO_%
611,27001,QUIBDÓ,27,CHOCÓ,14797.0,15559.0,16972.0,17773.0,16925.0,15374.0,13762.0,9193.0,10646.0,-4151.0,-28.052984
1137,76845,ULLOA,76,VALLE DEL CAUCA,3700.0,355.0,310.0,191.0,162.0,162.0,185.0,215.0,154.0,-3546.0,-95.837838
469,23417,LORICA,23,CÓRDOBA,4930.0,5907.0,5661.0,5592.0,4995.0,4425.0,3486.0,2294.0,3357.0,-1573.0,-31.906694
191,13657,SAN JUAN NEPOMUCENO,13,BOLÍVAR,1631.0,1795.0,1291.0,842.0,1127.0,1031.0,736.0,40.0,315.0,-1316.0,-80.686695
479,23660,SAHAGÚN,23,CÓRDOBA,5373.0,6213.0,6234.0,6742.0,6386.0,4355.0,4055.0,3202.0,4098.0,-1275.0,-23.729760
472,23466,MONTELÍBANO,23,CÓRDOBA,4485.0,4504.0,3965.0,3637.0,3613.0,3050.0,4851.0,1347.0,3400.0,-1085.0,-24.191750
1075,73408,LÉRIDA,73,TOLIMA,1184.0,1201.0,600.0,620.0,434.0,368.0,464.0,406.0,302.0,-882.0,-74.493243
436,20013,AGUSTÍN CODAZZI,20,CESAR,3315.0,4274.0,4150.0,4125.0,5252.0,5218.0,4591.0,2919.0,2534.0,-781.0,-23.559578
82,5579,PUERTO BERRÍO,5,ANTIOQUIA,3849.0,3623.0,3433.0,6627.0,11316.0,5988.0,4916.0,2118.0,3108.0,-741.0,-19.251754
262,15469,MONIQUIRÁ,15,BOYACÁ,678.0,370.0,993.0,1714.0,1746.0,105.0,90.0,2281.0,126.0,-552.0,-81.415929
1,5002,ABEJORRAL,5,ANTIOQUIA,962.0,1037.0,1074.0,24735.0,2230.0,2320.0,948.0,697.0,507.0,-455.0,-47.297297
1156,85162,MONTERREY,85,CASANARE,1721.0,328.0,1085.0,1445.0,1352.0,1256.0,3103.0,1272.0,1276.0,-445.0,-25.857060
62,5361,ITUANGO,5,ANTIOQUIA,998.0,1002.0,1030.0,1088.0,1236.0,1151.0,952.0,764.0,565.0,-433.0,-43.386774
1140,76890,YOTOCO,76,VALLE DEL CAUCA,1278.0,1219.0,1044.0,1090.0,716.0,1173.0,1608.0,1455.0,860.0,-418.0,-32.707355
1081,73483,NATAGAIMA,73,TOLIMA,670.0,640.0,547.0,703.0,717.0,608.0,535.0,392.0,293.0,-377.0,-56.268657
194,13673,SANTA CATALINA,13,BOLÍVAR,449.0,572.0,336.0,34.0,24.0,38.0,19.0,39.0,80.0,-369.0,-82.182628
643,27800,UNGUÍA,27,CHOCÓ,605.0,165.0,125.0,481.0,255.0,164.0,132.0,60.0,247.0,-358.0,-59.173554
84,5591,PUERTO TRIUNFO,5,ANTIOQUIA,1593.0,1784.0,1981.0,2064.0,1555.0,1240.0,1096.0,1732.0,1240.0,-353.0,-22.159448
919,63690,SALENTO,63,QUINDÍO,1609.0,499.0,451.0,654.0,665.0,560.0,836.0,946.0,1259.0,-350.0,-21.752641
475,23570,PUEBLO NUEVO,23,CÓRDOBA,659.0,1049.0,1063.0,1087.0,1409.0,2348.0,979.0,366.0,348.0,-311.0,-47.192716